accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import usersignup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", usersignup, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import TaskCreateView, TaskListView, TaskUpdateView


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(pattern_name="list_projects"), name="home"),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )
    assignee = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name="tasks"
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

# Create your views here.


def usersignup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # username/pw is extracted from the signup page(form)
            username = form.cleaned_data["username"]
            raw_password = make_password(form.cleaned_data.get("password"))
            # Store Encrypted password in db
            # user is created
            user = User.objects.create_user(username, raw_password)
            login(
                request,
                user,
                backend="django.contrib.auth.backends.ModelBackend",
            )  # login user after it's saved
            return redirect("home")
    # If request is not POST, then create an empty from and redirect to login
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list_projects.html"

    # In order to list projects which belong to the logged in user only
    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create_project.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        project = form.save()  # save form
        return redirect("show_project", pk=project.pk)

tasks/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        task = form.save()  # save form
        return redirect("show_project", pk=task.project.pk)


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "templates/task_detail.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My Tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>

projects/templates/projects/create_project.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create a new project</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
{% endblock content %}

projects/templates/projects/list_projects.html
{% extends 'base.html' %}
{% block content %}
    <h1>My Projects</h1>
    <p>
        <a href="{% url 'create_project' %}">Create a new project</a>
    </p>
    {% if project_list|length == 0 %}
        <p>You are not assigned to any projects</p>
    {% else %}
        <table>
            <thead>
                <th>Name</th>
                <th>Number of tasks</th>
            </thead>
            <tbody>
                {% for project in project_list %}
                    <tr>
                        <td>
                            <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a>
                        </td>
                        <td>{{ project.tasks.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock content %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %}
{% block content %}
    {% load markdownify %}
    <h1>{{ project.name }}</h1>
    <p>{{ project.description|markdownify  }}</p>
    <h2>Tasks</h2>
    <p>
        <a href="{% url 'create_task' %}">Create a new task</a>
    </p>
    {% if project.tasks.count %}
        <table>
            <thead>
                <th>Name</th>
                <th>Assignee</th>
                <th>Start date</th>
                <th>Due date</th>
                <th>Is completed</th>
            </thead>
            <tbody>
                {% for task in project.tasks.all %}
                    <tr>
                        <td>{{ task.name }}</td>
                        <td>{{ task.assignee }}</td>
                        <td>{{ task.start_date }}</td>
                        <td>{{ task.due_date }}</td>
                        {% if task.is_completed %}
                            <td>Yes</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>This project has no tasks</p>
    {% endif %}
{% endblock content %}

tasks/templates/tasks/task_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create a new task</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
{% comment %} comment {% endcomment %}
{% endblock content %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>My Tasks</h1>
    {% if task_list.count %}
        <table>
            <thead>
                <th>Name</th>
                <th>Start date</th>
                <th>End date</th>
                <th>Is completed</th>
            </thead>
            <tbody>
                {% for task in task_list %}
                    <tr>
                        <td>{{ task.name }}</td>
                        <td>{{ task.start_date }}</td>
                        <td>{{ task.due_date }}</td>
                        {% if task.is_completed %}
                            <td>Done</td>
                        {% else %}
                            <td>
                                <form method="post" action="{% url 'complete_task' task.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="is_completed" value="True">
                                    <button>Complete</button>
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You have no tasks</p>
    {% endif %}
{% endblock content %}